# Configuration for the rate limiter

# Define a list of rate limiters
limiters:
  - key: "api_rate_limit"
    algorithm: "fixed_window_counter"
    backend: "in_memory"
    window_params:
      window: 1m
      limit: 10

  - key: "user_login_rate_limit_distributed"
    algorithm: "sliding_window_counter"
    backend: "redis"
    window_params:
      window: 5m
      limit: 50
    redis_params:
      address: "localhost:6379"
      password: ""
      db: 0
