# Configuration for the rate limiter

# Define a list of rate limiters
limiters:
  - key: "api_rate_limit"
    algorithm: "fixed_window_counter"
    backend: "in_memory"
    window_params:
      window: 1m
      limit: 10

  - key: "user_login_rate_limit_distributed"
    algorithm: "sliding_window_counter"
    backend: "redis"
    window_params:
      window: 5m
      limit: 50
    redis_params:
      address: "localhost:6379"
      password: ""
      db: 0
      pool_size: 10
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s

  - key: "token_bucket_example"
    algorithm: "token_bucket"
    backend: "in_memory"
    token_bucket_params:
      rate: 10 # tokens per second
      capacity: 50

  # Example with Redis backend for Token Bucket
  - key: "token_bucket_redis_example"
    algorithm: "token_bucket"
    backend: "redis"
    token_bucket_params:
      rate: 5 # tokens per second
      capacity: 20
    redis_params:
      address: "localhost:6379"
      password: ""
      db: 0
      pool_size: 10
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s
