# Configuration for the rate limiter

# Define a list of rate limiters
limiters:
  - key: "api_rate_limit"
    algorithm: "fixed_window_counter"
    backend: "in_memory"
    window_params:
      window: 1m
      limit: 10

  - key: "user_login_rate_limit"
    algorithm: "sliding_window_counter"
    backend: "in_memory"
    window_params:
      window: 1m
      limit: 10

  # Add more limiter configurations here as needed
  # - key: "another_limiter"
  #   algorithm: "..."
  #   backend: "..."
  #   ...params...
