# Configuration for the rate limiter

limiter:
  key: "api_rate_limit"
  algorithm: "fixed_window_counter"
  backend: "in_memory"

  fixed_window_counter_params:
    window: 1m
    limit: 10

  # redis_params:
  #   address: "localhost:6379"
  #   password: ""
  #   db: 0
